sudo: required
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - make build
      - docker images
    - stage: test
      script:
      - make test
